import { Info } from 'lucide-react';

export function AIDisclaimer() {
  return (
    <footer className="mt-12 mb-6 px-4">
      <div className="max-w-5xl mx-auto">
        <div className="flex items-start gap-2.5 bg-slate-100/70 rounded-xl px-4 py-3 border border-slate-200">
          <Info className="w-4 h-4 text-slate-400 flex-shrink-0 mt-0.5" />
          <p className="text-xs text-slate-500 leading-relaxed">
            Content generated by SRC Content Studio is a draft or suggestion — not a final product.
            Always proofread and review before publishing or sending. AI can make mistakes, so use your
            judgment and verify facts, dates, and details.
          </p>
        </div>
      </div>
    </footer>
  );
}
